config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("godal_em.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("pages.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

godal_em/urls.py
from django.urls import path, include
from . import views

app_name = "godalem"

urlpatterns = [
    path("", views.index, name="index"),
    path("request-meter/", views.request_meter, name="request-meter"),
    path("buy-power/", views.buy_power, name="buy-power"),
    path("history/<int:id>/", views.history, name="history"),
]

pages/urls.py
from django.urls import path

from .views import HomePageView, AboutPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
#from godal_em.models import Region

class CustomUser(AbstractUser):
    house_number = models.CharField(max_length=100)
    #region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    city = models.CharField(max_length=50)
    area = models.CharField(max_length=100)
    digital_address = models.CharField(max_length=20)
    house_type = models.CharField(max_length=100)

    def __str__(self):
        return self.email

godal_em/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth import get_user_model
# Create your models here.

User = get_user_model()

class Region(models.Model):
    name = models.CharField(max_length=100)
    
class Meter(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, related_name="meter")
    meter_id = models.CharField(max_length=8, unique=True)
    current_power = models.IntegerField(default=0)
    active = models.BooleanField(default=False)

    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return self.meter_id

class Request(models.Model):
    by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    granted = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("granted",)

    def __str__(self) -> str:
        return ''.join(f"Request by: {self.by}")

    def save(self, *args, **kwargs) -> None:
        # if unique_id
        #self.invoice_id = str(self.supplier.id + unique_id(8))
        if self.granted:
            self.by.meter.current_power += self.amount
            self.by.meter.save()
        super().save(*args, **kwargs)

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email', 'username',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = (
            'first_name', 
            'last_name',
            'city',
            'area',
            'digital_address',
            'house_type',
        )

        

godal_em/forms.py
from dataclasses import field
from django import forms

from .models import Meter, Request

class RequestForm(forms.ModelForm):
    class Meta:
        model = Request
        fields = (
            "amount",
        )

accounts/views.py
from django.shortcuts import render

# Create your views here.

godal_em/views.py
from django.shortcuts import render, redirect, get_object_or_404
from accounts.forms import CustomUserChangeForm
from .models import Meter, Request
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import RequestForm
# Create your views here.
from random import randint
from django.contrib.auth import get_user_model

User = get_user_model()

def uniqueId(n):
    range_start = 10**(n-1)
    range_end = (10**n)-1
    return randint(range_start, range_end)

def index(request):
    return render(request, 'pages/index.html')

@login_required
def request_meter(request):
    if request.user.meter:
        messages.error(request, "sorry you already have a meter")
        return redirect('/')
    if request.method == 'POST':
        user_form = CustomUserChangeForm(data=request.POST, files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            Meter.objects.create(
                user = request.user,
                meter_id = uniqueId(8),
            ).save()
            user_form.save()
            messages.success(request, 'Your request have been sent, you will be notified once its approved.')
            return redirect("/")
        else:
            messages.error(request, 'Invalid data Entry, check and try again.')
    else:
        user_form = CustomUserChangeForm()
    
    return render(request, 'pages/request_meter.html', {
        'user_form': user_form,
    })

def buy_power(request):
    if request.method == "POST":
        form = RequestForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            power_form = form.save(commit=False)
            power_form.by = request.user
            power_form.save()
            messages.success(request, 'Request Sent. please standby')
            return redirect("/")
        else:
            messages.error(request, 'Invalid data Entry, check and try again.')
    else:
        user_form = RequestForm()
    
    return render(request, 'pages/buy_power.html', {
        'user_form': user_form,
    })

def secrete_route(request):
    return render(request, 'pages/dashboard.html')

def users(request):
    meters = Meter.objects.all()
    return render(request, 'pages/meters.html', {
        "meters": meters
    })

def history(request, id):
    user = get_object_or_404(User, id=id)
    requests = Request.objects.filter(by=user)
    return render(request, 'pages/history.html', {
        "requests": requests
    })

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "pages/home.html"


class AboutPageView(TemplateView):
    template_name = "pages/about.html"

templates/403_csrf.html
{% extends '_base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
  <title>{% block title %}Godal EC{% endblock title %}</title>
  <meta name="description" content="A framework for launching new Django projects quickly.">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

  {% block css %}
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  {% endblock %}
</head>

<body>
  <main role="main">
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="/">Godal EC</a>
      </h5>
      <!-- <a class="p-2 text-dark" href="">About</a> -->
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              {{ user.email }}
            </a>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
              <a class="dropdown-item" href="{% url 'account_change_password' %}">Change password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a>
            </div>
          </li>
        </ul>
        {% else %}
        <form class="form-inline ml-auto">
          <a href="{% url 'account_login' %}" class="btn btn-outline-secondary">Log in</a>
          <a href="{% url 'account_signup' %}" class="btn btn-primary ml-2">Sign up</a>
        </form>
        {% endif %}
      </nav>
    </div>
  </main>

  <div class="container">
    {% block content %}
    <p>Default content...</p>
    {% endblock content %}
  </div>

  <footer class="footer">
    <div class="container">
      <span class="text-muted">Footer...</span>
    </div>
  </footer>



  {% block javascript %}
  <!-- Bootstrap JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- 3rd party JavaScript -->

  <!-- Project JS -->
  <script src="{% static 'js/base.js' %}"></script>

  {% endblock javascript %}

</body>

</html>

templates/pages/about.html
{% extends '_base.html' %}

{% block title %}About page{% endblock %}

{% block content %}
<h1>About page</h1>
{% endblock content %}

templates/pages/buy_power.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Request Form{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card p-3">
                <h2>
                    Buy Power
                </h2>
                {% if not request.user.meter.active %}
                <p class="text-danger">
                    Note: You wont be able to use your Power until your metter is active.
                </p>
                {% endif %}
                <hr>
                <form method="post">
                    {% csrf_token %}

                    {{ user_form | crispy }}

                    <input type="submit" name="" value="Save" class="btn btn-success btn-md">
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock content %}

templates/pages/history.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Request Form{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h3>
                Power Requests
            </h3>
            <table class="table responsive">

                <thead class="thead-dark">
                    <th>#</th>
                    <th>Date</th>
                    <th>Amount</th>
                    <th>Granted</th>
                </thead>

                <tbody>
                    {% for req in requests %}
                    <tr>
                        <td>
                            {{ forloop.counter }}
                        </td>
                        <td>
                            {{ req.date_created }}
                        </td>
                        <td>
                            {{ req.amount }}
                        </td>
                        <td>
                            {% if req.granted %}

                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-check-circle-fill text-success" viewBox="0 0 16 16">
                                <path
                                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z" />
                            </svg>
                            {% else %}
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-x-circle-fill text-danger" viewBox="0 0 16 16">
                                <path
                                    d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293 5.354 4.646z" />
                            </svg>
                            {% endif %}

                        </td>
                    </tr>
                    {% endfor %}
                </tbody>

            </table>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock content %}

templates/pages/index.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Home page{% endblock title %}

{% block content %}
{% if request.user.meter %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8 p-3">
      {% if not request.user.meter.active %}
      <p class="text-danger">
        Sorry, your metter has not been approved yet.
      </p>
      {% endif %}
      <div class="card bg-dark text-white">
        <div class="card-body">
          <p>
            {% if request.user.meter.active %}
            <span class="bg-success text-white p-3">Active</span>
            {% else %}
            <span class="bg-danger text-white p-3">Inactive</span>

            {% endif %}
          </p>
          <hr>
          <h3 class="text-center">
            Meter #: {{ request.user.meter.meter_id }}
          </h3>
          <hr class="text-white color-white">
          <p>Available Current</p>
          <div>

            <div class="display-3">
              {{ request.user.meter.current_power }} W
            </div>
          </div>
          <hr>
          <div class="d-flex flex-row justify-content-between">
            <div>
              Usage: 35 W
            </div>
            <div>
              Up Time: <span id="minutes">00</span>: <span id="seconds">00</span>
            </div>

          </div>
        </div>
      </div>
      <div class="row mt-4">
        <a href="{% url 'godalem:buy-power' %}" class="btn btn-success btn-lg p-4 m-4">
          Buy Power
        </a>
        <a href="{% url 'godalem:history' request.user.id %}" class="btn btn-dark btn-lg p-4 m-4">
          History
        </a>
      </div>
    </div>

    <div class="col-md-2"></div>

  </div>


</div>
{% else %}
<div class="container">
  <div class="row">
    <div class="display-3">
      Welcome to GODAL EC
    </div>
    <p>
      Please request for a metter below
    </p>

  </div>
  <div class="row">
    <div>
      <a href="{% url 'godalem:request-meter' %}" class="btn btn-lg btn-dark">
        Request Meter
      </a>
    </div>
  </div>
</div>
{% endif %}

<script>
  var minutes = document.getElementById('minute');
  var seconds = document.getElementById('seconds');
  var totalSeconds = 0;
  setInterval(setTime, 1000);

  function setTime() {
    ++totalSeconds;
    seconds.innerHTML = pad(totalSeconds % 60);
    mintues.innerHTML = pad(parseInt(totalSeconds / 60));
  }

  function pad(value) {
    var valString = val + "";
    if (valString.length < 2) {
      return "0" + valString;
    } else {
      return valString;
    }
  }
</script>
{% endblock content %}

templates/pages/request_meter.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Request Form{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6">
            <div class="card p-3">
                <h2>
                    Request Meter Form
                </h2>
                <hr>
                <form method="post">
                    {% csrf_token %}

                    {{ user_form | crispy }}

                    <input type="submit" name="" value="Save" class="btn btn-success btn-md">
                </form>
            </div>
        </div>
        <div class="col-md-3"></div>
    </div>
</div>
{% endblock content %}